services:
  - name: node-backend
    type: web
    buildCommand: npm install && npm run build
    startCommand: node index.js
    github:
      branch: main
    healthCheckPath: /healthcheck

  - name: vue-frontend
    type: web
    buildCommand: cd frontend && npm install && npm run build
    startCommand: npx serve -s dist
    github:
      branch: main
    healthCheckPath: /